### PR TITLE
Improved algorithm for 'focusNextTextField'

### PR DESCRIPTION
**Pull request by AnthonyMDev**
This algorithm will  to more accurately select the next text field.
This works with all cases. Preferring the next text field that is to the right, then below the `priorTextField`.

This fixes cases such as this:

---------111111-
---------22222--
--333333333--

Previously, text field 3 would be chosen as the next text field in this case. This new algorithm selects text field 2.

### CODE REVIEW

**Comment by michaeltyson** [comment]
I'm afraid this breaks the sample app (jumps between incorrect views in the collection view)

**Comment by AnthonyMDev** [comment]
Really? I just tried it on the sample app, and it seemed to work. Let me check it out again.

**Comment by AnthonyMDev** [comment]
@michaeltyson I've just tried this again on both the simulator and my device, and the collection view sample seems to be working just fine for me. It should be going in numerical order, correct? Left, right, left, right, left, right?
That is the behavior I'm seeing. What are you seeing?

**Comment by michaeltyson** [comment]
If you open it up on the simulator, on the iPhone 5 in landscape, and visit the collection view screen (where it lays out the elements three per row), it skips the middle row, alas.

**Comment by AnthonyMDev** [comment]
Okay! thanks! I'll try that out, and see if I can fix it.
If I can get this working completely with the sample, would you pull it?

**Comment by michaeltyson** [comment]
I'd prefer to refine the existing algorithm where possible, as it's meant to be more general...

**Comment by AnthonyMDev** [comment]
Believe me, I spent 6 hours today trying to do just that. It was really cleverly crafted, but I couldn't find a way to make it work in every possible situation.
I've almost figured out the bug that I've got in my algorithm right now. If you don't want to pull it, I completely understand, as it is a huge deviation from what you are currently doing, but it is required for my work, so either way I'm going to finish it.

**Comment by michaeltyson** [comment]
No worries =) I'm just looking into it now

**Comment by AnthonyMDev** [comment]
I've got it where it seems like it is working now, in landscape or in portrait. But when I switch back and forth between orientations, it starts to act funny. I feel like it has something to do with the cells being laid out for the previous orientation. Any ideas on this?

**Comment by michaeltyson** [comment]
Try SHA 39494576a09b - should do the trick, I think. At least, it works with the layout I created from your description =)

**Comment by AnthonyMDev** [comment]
Well don't I feel stupid now. That works perfectly. Guess I greatly overthought it this time. Thank you so much @michaeltyson. You're a life saver.
Are you planning on pushing a new version of the pod with this?

**Comment by michaeltyson** [comment]
Hehe, cool! Happens to the best of us!

Yup, probably today; I'll just check the issue tracker to see if there's anything pressing first.

**Pull request closed without merging**
