### PR TITLE
Michaeltyson master

### PR DESCRIPTION
**Pull request by alexazhou**
restore the scroll offset when keyboard hide

### CODE REVIEW

**Comment by michaeltyson** [comment]
Hi! I'd rather not merge this in as it is, because the user may scroll during the edit operation, and if the scroll position is restored to the original after the keyboard is hidden, it may be bewildering to the user. Better to always do the "expected" thing, which is not scrolling to what the user will see as an arbitrary position.

Is this to work around a particular issue?

**Comment by alexazhou** [comment]
oh, in my App, the scrollview offset has changed after the keyboard hide, so I saved the original offset and restore it when keyboard hide.

**Comment by michaeltyson** [comment]
Are you able to reproduce it within the sample app, possibly with some changes?

**Comment by alexazhou** [comment]
I think I can try it,  but maybe need some time. I will comment to you when i finished. 
Have a nice day ~

**Comment by michaeltyson** [comment]
Okay, cool - thank you! You too!

**Pull request closed without merging**
