### PR TITLE
Prevent triggering contentSize when it's already the same, fix issue #155

### PR DESCRIPTION
**Pull request by Pash237**
Fixes this issue:
https://github.com/michaeltyson/TPKeyboardAvoiding/issues/155

### CODE REVIEW

**Comment by michaeltyson** [comment]
Thank you! But can you also apply the change to the other classes?

**Comment by Pash237** [comment]
There is already the same fix in TPKeyboardAvoidingCollectionView, but I can't reproduce it in the Scroll View.

**Comment by michaeltyson** [comment]
Ah, okay

**Comment by emwagner** [comment]
@Pash237 @michaeltyson  I'm still seeing issue #155  in my own project as well as in @Pash237 's demo project--dismissing the keyboard always scrolls the view all the way to the top, instead of returning it to the original scroll position. Are you guys able to reproduce it?

**Comment by Pash237** [comment]
@emwagner 
Demo project is demonstrating the issue, so you *should* see it there :)
There is commended out fix in TPKeyboardAvoidingTableView.m – please try to uncomment it.

If you're using CocoaPods, the fix is not in the podspec yet. But you can target specific commit:

    pod 'TPKeyboardAvoiding', :git => 'git@github.com:michaeltyson/TPKeyboardAvoiding.git', :commit => '87eaf03fae7b2dd3eff04ea27020f7e8637c71bb'

**Comment by emwagner** [comment]
@Pash237 Thanks! This is very helpful.

**Pull request merged**
